### ISSUE TITLE
Line breaks when y values have NAs

### ISSUE THREAD

**Issue by rabergj** [KopfLab/ggstackplot#13]
Line breaks appear when a given x value doesn't have a corresponding y value for each variable.

```{r}
# library(ggstackplot)
ggstackplot(
  mtcars |> 
    add_row(mpg = 22, wt = 5, qsec = NA, drat = NA, disp = NA),
  x = mpg,
  y = c(`weight [g]` = wt, qsec, drat, disp),
  color = c("#E41A1C", "#377EB8", "#4DAF4A", "#984EA3"),
  overlap = c(0.1, 0.3, 0)
)
```

![image](https://github.com/KopfLab/ggstackplot/assets/35500268/8c2613fa-9919-4bfe-8806-83d8ea5f3429)

Came across this when playing with my own data. Since the x values (Age) are generally different for different proxy records, this generates a lot of unwanted line breaks.

![image](https://github.com/KopfLab/ggstackplot/assets/35500268/28a2bae0-0b97-4c51-ae74-020fe81ea941)

**Comment by sebkopf** [comment]
@rabergj fixed in version 0.2.1, please test the new `remove_na` parameter, e.g.

```
library(ggstackplot)
library(dplyr)

# default
mtcars |> 
  add_row(mpg = 22, wt = 5, qsec = NA) |>
  ggstackplot(
    x = mpg, y = c(wt, qsec),
    color = c("#E41A1C", "#377EB8")
  )
```

![AXWPwkWcmbzOAAAAAElFTkSuQmCC](https://github.com/KopfLab/ggstackplot/assets/5498966/2da2e2b9-644e-424f-b0c8-6e864bfce190)

```
# explicit `remove_na` = FALSE
mtcars |> 
  add_row(mpg = 22, wt = 5, qsec = NA) |>
  ggstackplot(
    x = mpg, y = c(wt, qsec),
    color = c("#E41A1C", "#377EB8"),
    remove_na = FALSE
  )
#> Warning: There was 1 warning in `dplyr::mutate()`.
#> ℹ In argument: `gtable = map(.data$plot_w_theme, ggplot2::ggplotGrob)`.
#> Caused by warning:
#> ! Removed 1 rows containing missing values (`geom_point()`).
```

![h+foyKginXSnwAAAABJRU5ErkJggg==](https://github.com/KopfLab/ggstackplot/assets/5498966/eabb3fbe-211c-44bb-9b41-163387d2dc82)
